### ISSUE TITLE
报错 digital envelope routines:EVP_DecryptFinal_ex:wrong final block length

### ISSUE THREAD

**Issue by FastLight126** [limkim0530/czdb-search-node#2]
Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at Function.decrypt (D:\runtime\service\node_modules\czdb\lib\index.js:128:22)
    at Function.decrypt (D:\runtime\service\node_modules\czdb\lib\index.js:213:47)
    at new DbSearcher (D:\runtime\service\node_modules\czdb\lib\index.js:385:48)
    at _callee4$ (D:/runtime/service/other/cz88.js:101:15)
    at tryCatch (D:\runtime\service\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\runtime\service\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (D:\runtime\service\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\runtime\service\other\cz88.js:264:191)
    at D:\runtime\service\other\cz88.js:264:361 {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'wrong final block length',
  code: 'ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH'
}

**Comment by limkim0530** [comment]
It's been a while since we requested more details on this issue. I'll be closing this issue for now. If you have any updates later, you can always reopen it.
